development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/registrations/pay"
  email: eventos@jera.com.br

test:
  <<: *development

production:
  authenticity_token: 2948EE9A36FB404B8033439D643EDE40
  email: eventos@jera.com.br
  return_to: "http://maredeagilidade.jera.com.br/inscricao/registrations/pay"
