development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/registrations/pay"
  email: eventos@jera.com.br

test:
  <<: *development

production:
  authenticity_token: A582B0DAF0D14D0FBB98EF44F8311FDC
  email: eventos@jera.com.br
  return_to: "http://inscricao.maredeagilidade.jera.com.br/registrations/pay"
